name: Build and Deploy
on:
  push:
    branches:
      - phase04

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Install and Build ğŸ”§
        run: |
          mkdir -p build/style/css
          npm install
          npm run scss
          mv src/style/css build/style/
          cp src/pages build/pages -r
          cp src/script build/script -r
          cp src/assets build/assets -r

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: phase04
          folder: build
          target-folder: build
